nav:
  logo: https://smms.app/image/vJDIKrQSu65W2oP
  display_title: true
  fixed: false # fixed navigation bar

avatar:
  img: https://smms.app/image/vJDIKrQSu65W2oP
  effect: true # 头像会一直转圈

top_img: 'linear-gradient(20deg, #0062be, #925696, #cc426e, #fb0347)'

menu:
  首页: / || fas fa-home
  #時間軸: /archives/ || fas fa-archive
  #標籤: /tags/ || fas fa-tags
  #分類: /categories/ || fas fa-folder-open
  #清單||fa fa-heartbeat:
  #  音樂: /music/ || fas fa-music
  #  照片: /Gallery/ || fas fa-images
  #  電影: /movies/ || fas fa-video
  #友鏈: /link/ || fas fa-link
  #關於: /about/ || fas fa-heart

highlight_copy: true # show copy button in code block

social:
  fab fa-github: https://github.com/SecretLittleBoy || Github || "#hdhfbb"
  fas fa-envelope: mailto:2045918921@qq.com || Email || "#000000"


#这个搜索系统我们不开启，没必要用这么麻烦的
# Algolia search
algolia_search:
  enable: false
  hits:
    per_page: 6
#开启本地搜索，即可我们正常的使用
# Local search
local_search:
  enable: true
  preload: false
  CDN:
