nav:
  logo: ./logo.jpg
  display_title: true
  fixed: false # fixed navigation bar

menu:
  首页: / || fas fa-home
  #時間軸: /archives/ || fas fa-archive
  #標籤: /tags/ || fas fa-tags
  #分類: /categories/ || fas fa-folder-open
  #清單||fa fa-heartbeat:
  #  音樂: /music/ || fas fa-music
  #  照片: /Gallery/ || fas fa-images
  #  電影: /movies/ || fas fa-video
  #友鏈: /link/ || fas fa-link
  #關於: /about/ || fas fa-heart

highlight_copy: true # show copy button in code block

social:
  fab fa-github: https://github.com/SecretLittleBoy || Github || "#hdhfbb"
  fas fa-envelope: mailto:xxxxxx@gmail.com || Email || "#000000"